project:
  type: book
  
lang: pt-BR


book:
  title: "Análise de Regressão: Teoria e Prática"
  subtitle: "Departamento de Estatística e Matemática Aplicada"
  description: "Laboratório de Inovação em Estatística - StatLab"
  author: "Rafael Braz, Ronald Targino, Juvêncio Nobre e Manoel Santos-Neto"
  date: today
  chapters:
    - index.qmd
    - intro.qmd
    - preliminares.qmd
    - reg.qmd
    - pres.qmd
    - diag.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

